export const config = {
  OPENAI_API_KEY: import.meta.env.VITE_OPENAI_API_KEY,
  ELEVENLABS_API_KEY: import.meta.env.VITE_ELEVENLABS_API_KEY,
  ELEVENLABS_VOICE_ID: import.meta.env.VITE_ELEVENLABS_VOICE_ID,
  OPENAI_API_ENDPOINT: import.meta.env.VITE_OPENAI_API_ENDPOINT,
  WHISPER_API_ENDPOINT: import.meta.env.VITE_WHISPER_API_ENDPOINT,
  ELEVENLABS_API_ENDPOINT: import.meta.env.VITE_ELEVENLABS_API_ENDPOINT,
  BACKEND_URL: import.meta.env.VITE_BACKEND_URL
};
